# Generated by Django 5.0.3 on 2024-03-25 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(32),
                            django.core.validators.RegexValidator(
                                "^[a-z0-9]+(?:[_.-][a-z0-9]+)*$"
                            ),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AddField(
            model_name="track",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tracks", to="content.tag"
            ),
        ),
    ]
